site_name: 'Roadie Onboarding docs'
site_description: 'Documentation for using the Roadie application'

plugins:
  - techdocs-core

nav:
  - Getting started:
    - Installing the GitHub app: 'getting-started/install-github-app/index.md'
    - Adding components: 'getting-started/adding-components/index.md'
    - Using TechDocs: 'getting-started/technical-documentation/index.md'
    - Adding plugins: 'getting-started/configuring-backstage-plugins/index.md'
    - Inviting users: 'getting-started/user-management/index.md'
    - Designating admins: 'getting-started/create-admin-group/index.md'
    - Adding API specs: 'getting-started/openapi-specs/index.md'
    - Scaffolding components: 'getting-started/scaffolding-components/index.md'
  - Adding Backstage plugins:
    - Argo CD: 'integrations/argocd/index.md'
    - BuildKite: 'integrations/buildkite/index.md'
    - Bugsnag: 'integrations/bugsnag/index.md'
    - Catalog graph: 'integrations/catalog-graph/index.md'
    - CircleCI: 'integrations/circleci/index.md'
    - Datadog: 'integrations/datadog/index.md'
    - FireHydrant: 'integrations/firehydrant/index.md'
    - Google Cloud Platform: 'integrations/gcp/index.md'
    - GitHub org: 'integrations/github-org/index.md'
    - Github token: 'integrations/github-token/index.md'
    - Google oauth client: 'integrations/google-oauth-client/index.md'
    - Grafana: 'integrations/grafana/index.md'
    - Home Page: 'integrations/index.mdhome-page'
    - Home Page Markdown: 'integrations/index.mdhome-page-markdown'
    - Jenkins: 'integrations/jenkins/index.md'
    - Jira: 'integrations/jira/index.md'
    - Kubernetes: 'integrations/kubernetes/index.md'
    - Lighthouse: 'integrations/lighthouse/index.md'
    - Newrelic: 'integrations/newrelic/index.md'
    - Opsgenie: 'integrations/opsgenie/index.md'
    - PagerDuty: 'integrations/pagerduty/index.md'
    - Prometheus: 'integrations/prometheus/index.md'
    - Sentry: 'integrations/sentry/index.md'
    - Snyk: 'integrations/snyk/index.md'
    - Sonarqube: 'integrations/sonarqube/index.md'
    - Travis CI: 'integrations/travis-ci/index.md'
    - Tech radar: 'configuration/tech-radar/index.md'
    - Cortex: 'integrations/index.mdcortex'
  - Custom plugins:
    - Artifactory: 'custom-plugins/artifactory/index.md'
    - Configuring: 'custom-plugins/configuring/index.md'
    - Authenticated Proxy: 'custom-plugins/authenticated-proxy/index.md'
  - Details:
    - GitHub app permissions: 'integrations/github-app-permissions/index.md'
    - Setting secrets: 'details/setting-secrets/index.md'
    - Updating the UI: 'getting-started/updating-the-ui/index.md'
    - Allowlisting Roadie Traffic: 'details/allowlisting-roadie-traffic/index.md'
    - Required annotations: 'integrations/index.mdrequired-annotations'
