site_name: 'Roadie Onboarding docs'
site_description: 'Documentation for using the Roadie application'

plugins:
  - techdocs-core

nav:
  - Getting started:
    - Installing the GitHub app: 'getting-started/install-github-app/index.md'
    - Adding components: 'getting-started/adding-components/index.md'
    - Using TechDocs: 'getting-started/technical-documentation/index.md'
    - Adding plugins: 'getting-started/configuring-backstage-plugins/index.md'
    - Inviting users: 'getting-started/user-management/index.md'
    - Designating admins: 'getting-started/create-admin-group/index.md'
    - Adding API specs: 'getting-started/openapi-specs/index.md'
    - Scaffolding components: 'getting-started/scaffolding-components/index.md'
  - Backstage plugins:
    - Allure: 'integrations/allure/index.md'
    - Argo CD: 'integrations/argocd/index.md'
    - Azure DevOps: 'integrations/azure-devops/index.md'
    - BuildKite: 'integrations/buildkite/index.md'
    - Bugsnag: 'integrations/bugsnag/index.md'
    - Catalog graph: 'integrations/catalog-graph/index.md'
    - CircleCI: 'integrations/circleci/index.md'
    - Confluence: 'integrations/confluence/index.md'
    - Datadog: 'integrations/datadog/index.md'
    - FireHydrant: 'integrations/firehydrant/index.md'
    - Google Calendar: 'integrations/gcalendar/index.md'
    - Grafana: 'integrations/grafana/index.md'
    - Home Page: 'integrations/index.mdhome-page'
    - Home Page Markdown: 'integrations/index.mdhome-page-markdown'
    - IFrame: 'integrations/index.mdiframe'
    - Jenkins: 'integrations/jenkins/index.md'
    - Jira: 'integrations/jira/index.md'
    - Okta: 'integrations/okta/index.md'
    - Kubernetes: 'integrations/kubernetes/index.md'
    - Lighthouse: 'integrations/lighthouse/index.md'
    - Newrelic: 'integrations/newrelic/index.md'
    - Opsgenie: 'integrations/opsgenie/index.md'
    - PagerDuty: 'integrations/pagerduty/index.md'
    - Prometheus: 'integrations/prometheus/index.md'
    - Sentry: 'integrations/sentry/index.md'
    - Shortcut: 'integrations/shortcut-plugin/index.md'
    - Snyk: 'integrations/snyk/index.md'
    - Sonarqube: 'integrations/sonarqube/index.md'
    - Stackoverflow: 'integrations/index.mdstackoverflow'
    - Travis CI: 'integrations/travis-ci/index.md'
    - Tech radar: 'integrations/tech-radar/index.md'
    - Cortex: 'integrations/index.mdcortex'
  - Integrations:
    - AWS S3: 'integrations/aws-s3/index.md'
    - Bitbucket: 'integrations/bitbucket/index.md'
    - GitHub org: 'integrations/github-teams/index.md'
    - GitHub token: 'integrations/github-token/index.md'
    - Google Cloud Platform: 'integrations/gcp/index.md'
    - Google OAuth client: 'integrations/google-oauth-client/index.md'
  - Custom plugins:
    - Artifactory: 'custom-plugins/artifactory/index.md'
    - Configuring: 'custom-plugins/configuring/index.md'
    - Proxy: 'custom-plugins/proxy/index.md'
  - In-depth:
    - GitHub app permissions: 'details/github-app-permissions/index.md'
    - Configure GitHub Enterprise: 'details/github-enterprise/index.md'
    - Setting secrets: 'details/setting-secrets/index.md'
    - Updating the UI: 'details/updating-the-ui/index.md'
    - Accessing AWS resources: 'details/accessing-aws-resources/index.md'
    - Allowlisting Roadie traffic: 'details/allowlisting-roadie-traffic/index.md'
    - Modelling Users and Groups: 'details/modelling-users-and-groups/index.md'
    - Required annotations: 'details/required-annotations/index.md'
    - Previewing component changes: 'details/previewing-changes/index.md'
    - Validating catalog files: 'details/validator/index.md'
    - Removing components: 'details/unregister-components/index.md'
    - Accessing public resources: 'details/backend-reading-allow-list/index.md'
    - Requesting plugins: 'details/requesting-plugins/index.md'
    - Writing scaffolder templates: 'details/scaffolder/index.md'
    - Managing locations: 'details/location-management/index.md'
    - Modelling dependencies: 'details/showing-dependencies/index.md'
    - Troubleshooting the catalog: 'details/troubleshooting-the-catalog/index.md'
    - Using grpc-docs: 'details/grpc-docs/index.md'
