site_name: 'Roadie Onboarding docs'
site_description: 'Documentation for using the Roadie application'

plugins:
  - techdocs-core

nav:
  - Getting started:
    - Installing the GitHub app: 'getting-started/install-github-app/index.md'
    - Adding components: 'getting-started/adding-components/index.md'
    - Using TechDocs: 'getting-started/technical-documentation/index.md'
    - Adding plugins: 'getting-started/configuring-backstage-plugins/index.md'
    - Inviting users: 'getting-started/user-management/index.md'
    - Designating admins: 'getting-started/create-admin-group/index.md'
    - Adding API specs: 'getting-started/openapi-specs/index.md'
    - Scaffolding components: 'getting-started/scaffolding-components/index.md'
  - Adding Backstage plugins:
    - Argo CD: 'plugins/argocd/index.md'
    - BuildKite: 'plugins/buildkite/index.md'
    - Bugsnag: 'plugins/bugsnag/index.md'
    - Catalog graph: 'plugins/catalog-graph/index.md'
    - CircleCI: 'plugins/circleci/index.md'
    - Datadog: 'plugins/datadog/index.md'
    - FireHydrant: 'plugins/firehydrant/index.md'
    - Google Cloud Platform: 'plugins/gcp/index.md'
    - GitHub org: 'plugins/github-org/index.md'
    - Github token: 'plugins/github-token/index.md'
    - Google oauth client: 'plugins/google-oauth-client/index.md'
    - Grafana: 'plugins/grafana/index.md'
    - Home Page: 'plugins/index.mdhome-page'
    - Home Page Markdown: 'plugins/index.mdhome-page-markdown'
    - Jenkins: 'plugins/jenkins/index.md'
    - Jira: 'plugins/jira/index.md'
    - Kubernetes: 'plugins/kubernetes/index.md'
    - Lighthouse: 'plugins/lighthouse/index.md'
    - Newrelic: 'plugins/newrelic/index.md'
    - Opsgenie: 'plugins/opsgenie/index.md'
    - PagerDuty: 'plugins/pagerduty/index.md'
    - Prometheus: 'plugins/prometheus/index.md'
    - Sentry: 'plugins/sentry/index.md'
    - Snyk: 'plugins/snyk/index.md'
    - Sonarqube: 'plugins/sonarqube/index.md'
    - Travis CI: 'plugins/travis-ci/index.md'
    - Tech radar: 'configuration/tech-radar/index.md'
    - Cortex: 'plugins/index.mdcortex'
  - Custom plugins:
    - Artifactory: 'custom-plugins/artifactory/index.md'
    - Configuring: 'custom-plugins/configuring/index.md'
    - Authenticated Proxy: 'custom-plugins/authenticated-proxy/index.md'
  - Integrations:
      - S3: 'integrations/aws-s3/index.md'
  - Details:
    - GitHub app permissions: 'plugins/github-app-permissions/index.md'
    - Setting secrets: 'details/setting-secrets/index.md'
    - Updating the UI: 'getting-started/updating-the-ui/index.md'
    - Allowlisting Roadie Traffic: 'details/allowlisting-roadie-traffic/index.md'
    - Accessing your AWS Resources: 'details/accessing-aws-resources/index.md'
    - Required annotations: 'plugins/index.mdrequired-annotations'
