site_name: 'Roadie Onboarding docs'
site_description: 'Documentation for using the Roadie application'

plugins:
  - techdocs-core

nav:
  - Getting started:
      - Installing the GitHub app: 'getting-started/install-github-app/index.md'
      - Adding components: 'getting-started/adding-components/index.md'
      - Using TechDocs: 'getting-started/technical-documentation/index.md'
      - Adding plugins: 'getting-started/configuring-backstage-plugins/index.md'
      - Inviting users: 'getting-started/user-management/index.md'
      - Designating admins: 'getting-started/create-admin-group/index.md'
      - Modelling Users and Groups: 'getting-started/teams/index.md'
      - Adding API specs: 'getting-started/openapi-specs/index.md'
      - Scaffolding components: 'getting-started/scaffolding-components/index.md'
  - Backstage plugins:
      - Allure: 'integrations/allure/index.md'
      - Argo CD: 'integrations/argocd/index.md'
      - Azure DevOps: 'integrations/azure-devops/index.md'
      - Buildkite: 'integrations/buildkite/index.md'
      - Bugsnag: 'integrations/bugsnag/index.md'
      - Catalog graph: 'integrations/catalog-graph/index.md'
      - CircleCI: 'integrations/circleci/index.md'
      - Confluence: 'integrations/confluence/index.md'
      - Datadog: 'integrations/datadog/index.md'
      - FireHydrant: 'integrations/firehydrant/index.md'
      - Google Calendar: 'integrations/gcalendar/index.md'
      - Grafana: 'integrations/grafana/index.md'
      - Home Page: 'integrations/index.mdhome-page'
      - Home Page Markdown: 'integrations/index.mdhome-page-markdown'
      - IFrame: 'integrations/index.mdiframe'
      - Jenkins: 'integrations/jenkins/index.md'
      - Jira: 'integrations/jira/index.md'
      - Kubernetes: 'integrations/kubernetes/index.md'
      - Lighthouse: 'integrations/lighthouse/index.md'
      - Newrelic: 'integrations/newrelic/index.md'
      - Okta: 'integrations/okta/index.md'
      - Opsgenie: 'integrations/opsgenie/index.md'
      - PagerDuty: 'integrations/pagerduty/index.md'
      - Prometheus: 'integrations/prometheus/index.md'
      - Sentry: 'integrations/sentry/index.md'
      - Shortcut: 'integrations/shortcut-plugin/index.md'
      - Snyk: 'integrations/snyk/index.md'
      - Sonarqube: 'integrations/sonarqube/index.md'
      - Stackoverflow: 'integrations/index.mdstackoverflow'
      - Travis CI: 'integrations/travis-ci/index.md'
      - Tech radar: 'integrations/tech-radar/index.md'
      - Apache Airflow: 'integrations/apache-airflow/index.md'
  - Integrations:
      - AWS S3: 'integrations/aws-s3/index.md'
      - Azure DevOps: 'integrations/azure-devops-provider/index.md'
      - Broker: 'integrations/broker/index.md'
      - Microsoft Graph: 'integrations/ms-graph-org-provider/index.md'
      - Bitbucket: 'integrations/bitbucket/index.md'
      - GitHub Discovery: 'integrations/github-discovery/index.md'
      - GitHub org: 'integrations/github-teams/index.md'
      - GitHub token: 'integrations/github-token/index.md'
      - Google Cloud Platform: 'integrations/gcp/index.md'
      - Google OAuth client: 'integrations/google-oauth-client/index.md'
  - Custom plugins:
      - Configuration: 'custom-plugins/configuring/index.md'
      - Publishing Plugins: 'custom-plugins/artifactory/index.md'
      - Proxy: 'custom-plugins/proxy/index.md'
  - In-depth:
      - Accessing AWS resources: 'details/accessing-aws-resources/index.md'
      - Accessing public resources: 'details/backend-reading-allow-list/index.md'
      - Allowlisting Roadie traffic: 'details/allowlisting-roadie-traffic/index.md'
      - API docs custom renderers: 'details/custom-api-docs-renderers/index.md'
      - Configure GitHub Enterprise: 'details/github-enterprise/index.md'
      - GitHub app permissions: 'details/github-app-permissions/index.md'
      - Managing locations: 'details/location-management/index.md'
      - Modelling dependencies: 'details/showing-dependencies/index.md'
      - Previewing component changes: 'details/previewing-changes/index.md'
      - Required annotations: 'details/required-annotations/index.md'
      - Removing components: 'details/unregister-components/index.md'
      - Requesting plugins: 'details/requesting-plugins/index.md'
      - Setting secrets: 'details/setting-secrets/index.md'
      - Troubleshooting the catalog: 'details/troubleshooting-the-catalog/index.md'
      - Testing page configurations: 'details/sandbox-mode/index.md'
      - Using grpc-docs: 'details/grpc-docs/index.md'
      - Updating the UI: 'details/updating-the-ui/index.md'
      - Validating catalog files: 'details/validator/index.md'
      - Writing scaffolder templates: 'details/scaffolder/index.md'
  - Scaffolder-Cookbook:
      - Create RFC: 'scaffolder-cookbook/create-rfc/index.md'
      - Debug template: 'scaffolder-cookbook/debug-template/index.md'
      - Append file: 'scaffolder-cookbook/append/index.md'
      - Re-use Parameters: 'scaffolder-cookbook/global-constants/index.md'
      - Edit Files: 'scaffolder-cookbook/edit-file/index.md'
  - Tech-Insights:
      - Introduction: 'tech-insights/introduction/index.md'
      - Data Sources: 'tech-insights/data-sources/index.md'
      - Checks: 'tech-insights/checks/index.md'
      - Scorecards: 'tech-insights/scorecards/index.md'
